version: '3'

services:
  backend:
    image: backend:latest
    build: ./backend
    container_name: backend
    ports:
     - "8001:8001"
    environment:
    - PORT=8001

  frontend:
    image: frontend:latest
    container_name: frontend
    ports:
    - "3000:3000"