"""add category_id to orders

Revision ID: 347097fe12a1
Revises: 5e369b599d4f
Create Date: 2023-10-20 16:02:11.738143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347097fe12a1'
down_revision: Union[str, None] = '5e369b599d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'category_id')
    # ### end Alembic commands ###
