"""change name and surname types

Revision ID: 5e369b599d4f
Revises: 51615147f25c
Create Date: 2023-10-15 12:48:53.872757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e369b599d4f'
down_revision: Union[str, None] = '51615147f25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=31),
               existing_nullable=True)
    op.alter_column('users', 'surname',
               existing_type=sa.TEXT(),
               type_=sa.String(length=31),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'surname',
               existing_type=sa.String(length=31),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=31),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
