"""add check for balance

Revision ID: 71ce30d0f279
Revises: 90e17a2e7eb2
Create Date: 2023-10-08 23:38:16.289577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import column

# revision identifiers, used by Alembic.
revision: str = '71ce30d0f279'
down_revision: Union[str, None] = '90e17a2e7eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("ck_user_balance_positive", 'users', column("balance") >= 0)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_user_balance_positive", 'users')
    # ### end Alembic commands ###
