"""add balance and pending_money to user

Revision ID: 90e17a2e7eb2
Revises: a0b565662f9a
Create Date: 2023-10-08 23:04:26.844348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e17a2e7eb2'
down_revision: Union[str, None] = 'a0b565662f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('pending_money', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_money')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
