"""add paybacks table

Revision ID: c1fdf5477f70
Revises: 347097fe12a1
Create Date: 2023-11-02 22:38:59.516221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1fdf5477f70'
down_revision: Union[str, None] = '347097fe12a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paybacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=31), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('units', sa.String(length=31), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paybacks')
    # ### end Alembic commands ###
