"""add users_id to operations

Revision ID: c508d6794b13
Revises: 8cf51ae42928
Create Date: 2023-10-04 10:51:37.419741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c508d6794b13'
down_revision: Union[str, None] = '8cf51ae42928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'user_id')
    # ### end Alembic commands ###
